### Creación de usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nombre": "Jhonny B God",
    "contrasena": "55566677",
    "idtipousuario": 3
}

### Petición GET de prueba
GET http://localhost:3000

### Petición todos los usuarios
GET http://localhost:3000/api/users

### Petción usuario por id
GET http://localhost:3000/api/users/1

### Update usuario
PUT  http://localhost:3000/api/users/1
Content-Type: application/json

{
    "nombre": "Jane Doe"
}